### ISSUE TITLE
extension handling will let in no-extension paths

### ISSUE THREAD

**Issue by burhan** [aws-samples/amazon-bedrock-audio-summarizer#13]
The default logic for extracting the extension, will fail if the path has no extension:

```
>>> "source/foo".split(".")[-1]
'source/foo'
```

using [os.path.splitext](https://docs.python.org/3/library/os.path.html#os.path.splitext) provides better extension handling, as it will catch the above case.

**Comment by erikhopf** [comment]
@burhan going to close this issue since it looks like @jbnunn merged your PR. Happy to re-open this if needed, just let me know.
