### ISSUE TITLE
eventbridge-bedrock-inference 

### ISSUE THREAD

**Issue by sanchep2** [aws-samples/amazon-bedrock-audio-summarizer#15]
I follow the step by step guide 
and After uploading the file I get `transcription` folder created  but the `processed` Folder is never created 

looking at the `/aws/lambda/eventbridge-bedrock-inference` Cloudwatch logs I see the following log event 

``` 
2024-08-14T20:22:05.431Z
[ERROR]	2024-08-14T20:22:05.431Z	930587f4-631c-4afc-81dd-840def9cc233	An error occurred (AccessDeniedException) when calling the InvokeModel operation: You don't have access to the model with the specified model ID.
``` 

just after 
```
[INFO]	2024-08-14T20:22:04.916Z	930587f4-631c-4afc-81dd-840def9cc233	## INVOKING MODEL
```

any Idea how to solve it ?

**Comment by jbnunn** [comment]
Hi @sanchep2 -- yes, the error "You don't have access to the model with the specified model ID" means you'll need to request access to the Claude 3 Sonnet model in Bedrock for the script to work. Instructions for requesting access can be found at: https://docs.aws.amazon.com/bedrock/latest/userguide/model-access.html

Alternatively, if you already have access to a model you want to try, you could update the code at https://github.com/aws-samples/amazon-bedrock-audio-summarizer/blob/main/lambda/eventbridge-bedrock-inference/lambda_function.py#L199

**Comment by sanchep2** [comment]
Thanks 
that was the resolution @jbnunn
