### ISSUE TITLE
An error occurred (ValidationException) when calling the InvokeModel operation: Your account is not authorized to invoke this API operation.

### ISSUE THREAD

**Issue by fdhome** [aws-samples/amazon-bedrock-audio-summarizer#3]
Hello,

I follow all instructions to setup this project but the eventbridge-bedrock-inference is always failing with the following error

- An error occurred (ValidationException) when calling the InvokeModel operation: Your account is not authorized to invoke this API operation.

I made sure to enable access to Anthropic's Claude 3 Sonnet via the AWS Bedrock Console and the access has been granted for my IAM User

As per documentation, the ValidationException with InvokeModel operation means that the call schema is incorrect.

Any help, things to check and correct are welcomed

**Comment by jbnunn** [comment]
Hi @fdhome, could you check to see if your IAM user has [`InvokeModel` permissions for BedRock?](https://github.com/aws-samples/amazon-bedrock-audio-summarizer/blob/f218fea0ecb5809c826c0b60d12caf27a486539d/summarizer/summarizer_stack.py#L55)

**Comment by fdhome** [comment]
Hello,

The main issue was between the screen and the chair ;-) the model access to Anthropic's Claude 3 Sonnet was provided for us-east-1 region whilst I was deploying in 2 others regions.
When deploying in the region in which model access has been granted it works like a charm.
great job there
issue can be cloased

**Comment by jbnunn** [comment]
Thanks @fdhome for the details, glad you got it working! We'll make the README a bit more clear.
